name: Build and push to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runTest:
        description: 'Run Tests'
        type: boolean
        default: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'MERGE_ONLY')"
    uses: actions/setup-python@v1
    steps:
      - name: Message
        run: | 
          echo "Deployed"
