# .github/workflows/logger.yaml
name: Event Loggger 1
on: push

jobs:
  log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    if: "!contains(github.event.head_commit.message, 'MERGE-ONLY')"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"