name: Build and push to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: "!contains(github.event.head_commit.title, 'MERGE-ONLY')"
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Message
        run: | 
          echo "Deployed"
          echo ${{github.event}}