name: Build and push to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: "!contains(${{ github.event.pull_request.title }}, 'MERGE-ONLY')"
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Message
        run: | 
          echo "Deployed"